/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/zhihu/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zhihu Callback */
        get: operations["zhihu_callback_auth_zhihu_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/zhihu/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zhihu Login Url */
        get: operations["zhihu_login_url_auth_zhihu_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mine */
        get: operations["list_mine_exchanges_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges/{exchange_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exchange */
        get: operations["get_exchange_exchanges__exchange_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges/{exchange_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Exchange */
        post: operations["close_exchange_exchanges__exchange_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges/{exchange_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_exchanges__exchange_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_exchanges__exchange_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Condition */
        post: operations["submit_condition_match_conditions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/conditions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Condition */
        post: operations["cancel_condition_match_conditions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/conditions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Condition */
        get: operations["current_condition_match_conditions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/articles/browser-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture From Browser */
        post: operations["capture_from_browser_me_articles_browser_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/articles/failed-fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Failed Fetch */
        get: operations["list_failed_fetch_me_articles_failed_fetch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/articles/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Archive Queue */
        get: operations["list_archive_queue_me_articles_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases */
        get: operations["list_knowledge_bases_me_knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_me_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/knowledge-bases/{knowledge_base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base */
        get: operations["get_knowledge_base_me_knowledge_bases__knowledge_base_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Base */
        delete: operations["delete_knowledge_base_me_knowledge_bases__knowledge_base_id__delete"];
        options?: never;
        head?: never;
        /** Patch Knowledge Base */
        patch: operations["patch_knowledge_base_me_knowledge_bases__knowledge_base_id__patch"];
        trace?: never;
    };
    "/me/knowledge-bases/{knowledge_base_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Base Articles */
        get: operations["list_knowledge_base_articles_me_knowledge_bases__knowledge_base_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/knowledge-bases/{knowledge_base_id}/articles/browser-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Knowledge Base Article */
        post: operations["capture_knowledge_base_article_me_knowledge_bases__knowledge_base_id__articles_browser_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/knowledge-bases/{knowledge_base_id}/articles/failed-fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Base Failed Fetch */
        get: operations["list_knowledge_base_failed_fetch_me_knowledge_bases__knowledge_base_id__articles_failed_fetch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/knowledge-bases/{knowledge_base_id}/articles/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Base Queue */
        get: operations["list_knowledge_base_queue_me_knowledge_bases__knowledge_base_id__articles_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/portrait/self-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self Report */
        post: operations["self_report_me_portrait_self_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/portrait/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Portrait */
        post: operations["sync_portrait_me_portrait_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/reputation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Reputation */
        get: operations["me_reputation_me_reputation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review */
        post: operations["create_review_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArchiveQueueView
         * @description 工作台队列：未就绪正文 + 计数。capture_token 仅在仍有待补抓时下发。
         */
        ArchiveQueueView: {
            /**
             * Capture Token
             * @default
             */
            capture_token: string;
            /**
             * Failed Count
             * @default 0
             */
            failed_count: number;
            /** Items */
            items?: components["schemas"]["ArticleArchiveView"][];
            /**
             * Pending Count
             * @default 0
             */
            pending_count: number;
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
        };
        /** ArticleArchiveView */
        ArticleArchiveView: {
            /** Error Class */
            error_class?: string | null;
            /** Id */
            id: string;
            /** Source Url */
            source_url: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** AuthorizeUrlData */
        AuthorizeUrlData: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** BrowserCaptureBody */
        BrowserCaptureBody: {
            /** Html */
            html: string;
            /** Source Url */
            source_url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Token */
            token: string;
        };
        /** CreateReviewBody */
        CreateReviewBody: {
            /**
             * Exchange Id
             * Format: uuid
             */
            exchange_id: string;
        };
        /**
         * Eligibility
         * @enum {string}
         */
        Eligibility: "active" | "suspended";
        /**
         * ExchangeStatus
         * @enum {string}
         */
        ExchangeStatus: "open" | "closed";
        /** ExchangeView */
        ExchangeView: {
            /** Closed At */
            closed_at?: string | null;
            /**
             * Closes At
             * Format: date-time
             */
            closes_at: string;
            /** Id */
            id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            status: components["schemas"]["ExchangeStatus"];
            /** User A Id */
            user_a_id: string;
            /** User B Id */
            user_b_id: string;
        };
        /** FailedFetchListView */
        FailedFetchListView: {
            /**
             * Capture Token
             * @default
             */
            capture_token: string;
            /** Items */
            items?: components["schemas"]["ArticleArchiveView"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeBaseCreateBody */
        KnowledgeBaseCreateBody: {
            /** Collection Name */
            collection_name?: string | null;
            /** Name */
            name: string;
            /** Storage Profile Id */
            storage_profile_id?: string | null;
        };
        /** KnowledgeBasePatchBody */
        KnowledgeBasePatchBody: {
            /** Collection Name */
            collection_name?: string | null;
            /** Name */
            name?: string | null;
            /** Storage Profile Id */
            storage_profile_id?: string | null;
        };
        /** KnowledgeBaseView */
        KnowledgeBaseView: {
            /** Collection Name */
            collection_name: string;
            /** Embedding Model */
            embedding_model: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Storage Profile Id */
            storage_profile_id?: string | null;
        };
        /** ListResponse[MessageView] */
        ListResponse_MessageView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /**
             * Data
             * @description 业务数据列表
             */
            data?: components["schemas"]["MessageView"][];
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Page
             * @description 当前页码,从 1 开始
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页条数;0 表示不分页
             * @default 0
             */
            page_size: number;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
            /**
             * Total
             * @description 数据总数
             * @default 0
             */
            total: number;
        };
        /** ListResponse[PairView] */
        ListResponse_PairView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /**
             * Data
             * @description 业务数据列表
             */
            data?: components["schemas"]["PairView"][];
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Page
             * @description 当前页码,从 1 开始
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页条数;0 表示不分页
             * @default 0
             */
            page_size: number;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
            /**
             * Total
             * @description 数据总数
             * @default 0
             */
            total: number;
        };
        /**
         * MatchConditionStatus
         * @enum {string}
         */
        MatchConditionStatus: "waiting" | "matched" | "cancelled";
        /** MatchConditionView */
        MatchConditionView: {
            /** Id */
            id: string;
            /** Pair Closes At */
            pair_closes_at?: string | null;
            /** Pair Id */
            pair_id?: string | null;
            peer?: components["schemas"]["MatchPeerView"] | null;
            status: components["schemas"]["MatchConditionStatus"];
            /** Waiting Until */
            waiting_until?: string | null;
            want_tag: components["schemas"]["StrengthTag"];
            /** Want Text */
            want_text: string;
        };
        /** MatchPeerView */
        MatchPeerView: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Strengths */
            strengths?: components["schemas"]["StrengthTag"][];
            want_tag: components["schemas"]["StrengthTag"];
            /** Want Text */
            want_text: string;
        };
        /** MessageView */
        MessageView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exchange Id */
            exchange_id: string;
            /** Id */
            id: string;
            /** Sender Id */
            sender_id: string;
            /** Text */
            text: string;
        };
        /**
         * PairView
         * @description 配上之后给会话列表看的对方名片。
         */
        PairView: {
            /** Exchange Id */
            exchange_id: string;
            /** Peer Avatar Url */
            peer_avatar_url?: string | null;
            /** Peer Id */
            peer_id: string;
            /** Peer Name */
            peer_name: string;
            /** Peer Strengths */
            peer_strengths?: components["schemas"]["StrengthTag"][];
            /** Peer Want Text */
            peer_want_text: string;
        };
        /**
         * PortraitHorizon
         * @description 画像时间窗：长期稳定 vs 近 7 天。
         * @enum {string}
         */
        PortraitHorizon: "stable" | "recent_7d";
        /**
         * PortraitSource
         * @description 擅长从哪来。创作优先，否则用收藏；都没有才允许自报。
         * @enum {string}
         */
        PortraitSource: "contents" | "favorites" | "self_reported";
        /** PortraitView */
        PortraitView: {
            horizon: components["schemas"]["PortraitHorizon"];
            /** Strengths */
            strengths?: components["schemas"]["Strength"][];
        };
        /** ReputationView */
        ReputationView: {
            /** @default active */
            eligibility: components["schemas"]["Eligibility"];
            /**
             * Min Active Score
             * @default 60
             */
            min_active_score: number;
            /**
             * Score
             * @default 65
             */
            score: number;
            /**
             * Score Max
             * @default 100
             */
            score_max: number;
            /** Suspended Until */
            suspended_until?: string | null;
        };
        /** Response[ArchiveQueueView] */
        Response_ArchiveQueueView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["ArchiveQueueView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[ArticleArchiveView] */
        Response_ArticleArchiveView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["ArticleArchiveView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[AuthorizeUrlData] */
        Response_AuthorizeUrlData_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["AuthorizeUrlData"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[ExchangeView] */
        Response_ExchangeView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["ExchangeView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[FailedFetchListView] */
        Response_FailedFetchListView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["FailedFetchListView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[KnowledgeBaseView] */
        Response_KnowledgeBaseView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["KnowledgeBaseView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[MatchConditionView] */
        Response_MatchConditionView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["MatchConditionView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[MessageView] */
        Response_MessageView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["MessageView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[NoneType] */
        Response_NoneType_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /**
             * Data
             * @description 业务数据
             */
            data?: null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[ReputationView] */
        Response_ReputationView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["ReputationView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[ReviewView] */
        Response_ReviewView_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["ReviewView"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[UserCard] */
        Response_UserCard_: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /** @description 业务数据 */
            data?: components["schemas"]["UserCard"] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[list[ArticleArchiveView]] */
        Response_list_ArticleArchiveView__: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /**
             * Data
             * @description 业务数据
             */
            data?: components["schemas"]["ArticleArchiveView"][] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /** Response[list[KnowledgeBaseView]] */
        Response_list_KnowledgeBaseView__: {
            /**
             * Code
             * @description 业务状态码:成功 200,失败非 200
             * @default 200
             */
            code: number;
            /**
             * Data
             * @description 业务数据
             */
            data?: components["schemas"]["KnowledgeBaseView"][] | null;
            /**
             * Message
             * @description 提示信息
             * @default success
             */
            message: string;
            /**
             * Timestamp
             * @description 响应时间;默认不携带,不携带时省略
             */
            timestamp?: string | null;
        };
        /**
         * ReviewVerdict
         * @description 人先点不满意，模型只回答是不是真的差。
         * @enum {string}
         */
        ReviewVerdict: "poor" | "good" | "unclear";
        /** ReviewView */
        ReviewView: {
            /** Exchange Id */
            exchange_id: string;
            /** Id */
            id: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Reviewee Id */
            reviewee_id: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Score */
            score?: number | null;
            verdict: components["schemas"]["ReviewVerdict"];
        };
        /** SelfReportBody */
        SelfReportBody: {
            /** Tags */
            tags: components["schemas"]["StrengthTag"][];
        };
        /** SendMessageBody */
        SendMessageBody: {
            /** Text */
            text: string;
        };
        /** Strength */
        Strength: {
            /** Evidence Title */
            evidence_title?: string | null;
            /** Evidence Url */
            evidence_url?: string | null;
            source: components["schemas"]["PortraitSource"];
            tag: components["schemas"]["StrengthTag"];
        };
        /**
         * StrengthTag
         * @description 擅长 / 本次想学的闭集标签。匹配只在这个集合里做双向覆盖。
         * @enum {string}
         */
        StrengthTag: "编程" | "互联网" | "健身" | "运动训练" | "职场" | "学业" | "理财" | "写作" | "设计" | "医学健康" | "法律" | "其他";
        /** SubmitConditionBody */
        SubmitConditionBody: {
            want_tag: components["schemas"]["StrengthTag"];
            /** Want Text */
            want_text: string;
        };
        /** UserCard */
        UserCard: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Portraits */
            portraits?: components["schemas"]["PortraitView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_NoneType_"];
                };
            };
        };
    };
    zhihu_callback_auth_zhihu_callback_get: {
        parameters: {
            query?: {
                authorization_code?: string | null;
                code?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zhihu_login_url_auth_zhihu_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_AuthorizeUrlData_"];
                };
            };
        };
    };
    list_mine_exchanges_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_PairView_"];
                };
            };
        };
    };
    get_exchange_exchanges__exchange_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exchange_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ExchangeView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_exchange_exchanges__exchange_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exchange_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ExchangeView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_exchanges__exchange_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exchange_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_MessageView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_exchanges__exchange_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exchange_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MessageView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_condition_match_conditions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitConditionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MatchConditionView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_condition_match_conditions_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MatchConditionView_"];
                };
            };
        };
    };
    current_condition_match_conditions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MatchConditionView_"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserCard_"];
                };
            };
        };
    };
    capture_from_browser_me_articles_browser_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserCaptureBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ArticleArchiveView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_failed_fetch_me_articles_failed_fetch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_FailedFetchListView_"];
                };
            };
        };
    };
    list_archive_queue_me_articles_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ArchiveQueueView_"];
                };
            };
        };
    };
    list_knowledge_bases_me_knowledge_bases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_KnowledgeBaseView__"];
                };
            };
        };
    };
    create_knowledge_base_me_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_KnowledgeBaseView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_base_me_knowledge_bases__knowledge_base_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_KnowledgeBaseView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_base_me_knowledge_bases__knowledge_base_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_knowledge_base_me_knowledge_bases__knowledge_base_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBasePatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_KnowledgeBaseView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_base_articles_me_knowledge_bases__knowledge_base_id__articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_ArticleArchiveView__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_knowledge_base_article_me_knowledge_bases__knowledge_base_id__articles_browser_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserCaptureBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ArticleArchiveView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_base_failed_fetch_me_knowledge_bases__knowledge_base_id__articles_failed_fetch_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_FailedFetchListView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_base_queue_me_knowledge_bases__knowledge_base_id__articles_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ArchiveQueueView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    self_report_me_portrait_self_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfReportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserCard_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_portrait_me_portrait_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserCard_"];
                };
            };
        };
    };
    me_reputation_me_reputation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ReputationView_"];
                };
            };
        };
    };
    create_review_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ReviewView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
