"""产品常量。成色规则见 #59，只有 reputation 模块改分。"""

REPUTATION_SCORE_MAX = 100
REPUTATION_INITIAL_SCORE = 65
REPUTATION_POOR_DELTA = 5
REPUTATION_GOOD_DELTA = 1
REPUTATION_MIN_ACTIVE_SCORE = 60
REPUTATION_POOR_WINDOW_DAYS = 30
REPUTATION_POOR_COUNT_TO_SUSPEND = 2
REPUTATION_SUSPEND_DAYS = 7

PORTRAIT_RECENT_DAYS = 7
PORTRAIT_SYNC_STALE_DAYS = 7
PORTRAIT_SYNC_PENDING_TTL_SEC = 3600
PORTRAIT_SYNC_SCAN_INTERVAL_SEC = 3600
PORTRAIT_SYNC_SCAN_LIMIT = 50
MATCH_WAIT_HOURS = 24
PAIR_WINDOW_HOURS = 24
RETRIEVAL_CHUNK_CHARS = 500
RETRIEVAL_CHUNK_OVERLAP = 80
RETRIEVAL_TOP_K = 20
RETRIEVAL_MIN_SCORE = 0.2
MAX_EVIDENCE_EXCERPT = 400

QUALITY_SCORE_MIN = 0
QUALITY_SCORE_MAX = 100
QUALITY_POOR_BELOW = 60
QUALITY_GOOD_ABOVE = 80
