"""产品常量。声望规则见 #30 / #31，只有 reputation 模块改分。"""

REPUTATION_INITIAL_SCORE = 3
REPUTATION_POOR_DELTA = 1
REPUTATION_MIN_ACTIVE_SCORE = 1
REPUTATION_POOR_WINDOW_DAYS = 30
REPUTATION_POOR_COUNT_TO_SUSPEND = 2
REPUTATION_SUSPEND_DAYS = 7

PORTRAIT_RECENT_DAYS = 7
MATCH_WAIT_HOURS = 24
PAIR_WINDOW_HOURS = 24
