"""产品常量。成色规则见 #59，只有 reputation 模块改分。"""

REPUTATION_SCORE_MAX = 100
REPUTATION_INITIAL_SCORE = 65
REPUTATION_POOR_DELTA = 5
REPUTATION_GOOD_DELTA = 1
REPUTATION_MIN_ACTIVE_SCORE = 60
REPUTATION_POOR_WINDOW_DAYS = 30
REPUTATION_POOR_COUNT_TO_SUSPEND = 2
REPUTATION_SUSPEND_DAYS = 7

PORTRAIT_RECENT_DAYS = 7
MATCH_WAIT_HOURS = 24
PAIR_WINDOW_HOURS = 24

QUALITY_SCORE_MIN = 0
QUALITY_SCORE_MAX = 100
QUALITY_POOR_BELOW = 60
QUALITY_GOOD_ABOVE = 80
